import { z } from "zod";
export declare const EnvironmentSchema: z.ZodObject<{
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "production", "test", "staging"]>>;
    PORT: z.ZodDefault<z.ZodNumber>;
    API_PREFIX: z.ZodDefault<z.ZodString>;
    DATABASE_URL: z.ZodString;
    REDIS_URL: z.ZodString;
    NATS_URL: z.ZodOptional<z.ZodString>;
    JWT_PRIVATE_KEY_PATH: z.ZodDefault<z.ZodString>;
    JWT_PUBLIC_KEY_PATH: z.ZodDefault<z.ZodString>;
    JWT_ACCESS_EXPIRATION: z.ZodDefault<z.ZodString>;
    JWT_REFRESH_EXPIRATION: z.ZodDefault<z.ZodString>;
    S3_ENDPOINT: z.ZodString;
    S3_REGION: z.ZodDefault<z.ZodString>;
    S3_BUCKET: z.ZodDefault<z.ZodString>;
    S3_ACCESS_KEY: z.ZodString;
    S3_SECRET_KEY: z.ZodString;
    S3_FORCE_PATH_STYLE: z.ZodDefault<z.ZodBoolean>;
    RAZORPAY_KEY_ID: z.ZodString;
    RAZORPAY_KEY_SECRET: z.ZodString;
    RAZORPAY_WEBHOOK_SECRET: z.ZodString;
    FIREBASE_PROJECT_ID: z.ZodOptional<z.ZodString>;
    WHATSAPP_API_URL: z.ZodOptional<z.ZodString>;
    WHATSAPP_API_TOKEN: z.ZodOptional<z.ZodString>;
    WHATSAPP_SENDER_NUMBER: z.ZodOptional<z.ZodString>;
    SMTP_HOST: z.ZodDefault<z.ZodString>;
    SMTP_PORT: z.ZodDefault<z.ZodNumber>;
    SMTP_USER: z.ZodOptional<z.ZodString>;
    SMTP_PASSWORD: z.ZodOptional<z.ZodString>;
    EMAIL_FROM: z.ZodDefault<z.ZodString>;
    OTEL_EXPORTER_OTLP_ENDPOINT: z.ZodDefault<z.ZodString>;
    OTEL_SERVICE_NAME: z.ZodDefault<z.ZodString>;
    PAN_ENCRYPTION_KEY: z.ZodString;
}, "strip", z.ZodTypeAny, {
    NODE_ENV: "development" | "production" | "test" | "staging";
    PORT: number;
    API_PREFIX: string;
    DATABASE_URL: string;
    REDIS_URL: string;
    JWT_PRIVATE_KEY_PATH: string;
    JWT_PUBLIC_KEY_PATH: string;
    JWT_ACCESS_EXPIRATION: string;
    JWT_REFRESH_EXPIRATION: string;
    S3_ENDPOINT: string;
    S3_REGION: string;
    S3_BUCKET: string;
    S3_ACCESS_KEY: string;
    S3_SECRET_KEY: string;
    S3_FORCE_PATH_STYLE: boolean;
    RAZORPAY_KEY_ID: string;
    RAZORPAY_KEY_SECRET: string;
    RAZORPAY_WEBHOOK_SECRET: string;
    SMTP_HOST: string;
    SMTP_PORT: number;
    EMAIL_FROM: string;
    OTEL_EXPORTER_OTLP_ENDPOINT: string;
    OTEL_SERVICE_NAME: string;
    PAN_ENCRYPTION_KEY: string;
    NATS_URL?: string | undefined;
    FIREBASE_PROJECT_ID?: string | undefined;
    WHATSAPP_API_URL?: string | undefined;
    WHATSAPP_API_TOKEN?: string | undefined;
    WHATSAPP_SENDER_NUMBER?: string | undefined;
    SMTP_USER?: string | undefined;
    SMTP_PASSWORD?: string | undefined;
}, {
    DATABASE_URL: string;
    REDIS_URL: string;
    S3_ENDPOINT: string;
    S3_ACCESS_KEY: string;
    S3_SECRET_KEY: string;
    RAZORPAY_KEY_ID: string;
    RAZORPAY_KEY_SECRET: string;
    RAZORPAY_WEBHOOK_SECRET: string;
    PAN_ENCRYPTION_KEY: string;
    NODE_ENV?: "development" | "production" | "test" | "staging" | undefined;
    PORT?: number | undefined;
    API_PREFIX?: string | undefined;
    NATS_URL?: string | undefined;
    JWT_PRIVATE_KEY_PATH?: string | undefined;
    JWT_PUBLIC_KEY_PATH?: string | undefined;
    JWT_ACCESS_EXPIRATION?: string | undefined;
    JWT_REFRESH_EXPIRATION?: string | undefined;
    S3_REGION?: string | undefined;
    S3_BUCKET?: string | undefined;
    S3_FORCE_PATH_STYLE?: boolean | undefined;
    FIREBASE_PROJECT_ID?: string | undefined;
    WHATSAPP_API_URL?: string | undefined;
    WHATSAPP_API_TOKEN?: string | undefined;
    WHATSAPP_SENDER_NUMBER?: string | undefined;
    SMTP_HOST?: string | undefined;
    SMTP_PORT?: number | undefined;
    SMTP_USER?: string | undefined;
    SMTP_PASSWORD?: string | undefined;
    EMAIL_FROM?: string | undefined;
    OTEL_EXPORTER_OTLP_ENDPOINT?: string | undefined;
    OTEL_SERVICE_NAME?: string | undefined;
}>;
export type AppEnvironment = z.infer<typeof EnvironmentSchema>;
export declare function validateEnvironment(env?: Record<string, unknown>): AppEnvironment;
